### ISSUE TITLE
Linux build: Dependency sys/sysctl.h is deprecated

### ISSUE THREAD

**Issue by fieserWolF** [slajerek/MTEngineSDL#2]
**Describe the bug**
Compilation fails on Debian 5.14.9-2 (2021-10-03) x86_64 GNU/Linux .

**Console output**
MTEngineSDL/platform/Linux/src.Linux/main.cpp:13:10: fatal error: sys/sysctl.h: Not found.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version Debian 5.14.9-2 (2021-10-03) x86_64 GNU/Linux

**Additional context**
Dependency sys/sysctl.h is deprecated.
Fix: Simply comment out line 13 in MTEngineSDL/platform/Linux/src.Linux/main.cpp :
// #include <sys/sysctl.h>

Keep up the good work!

**Comment by slajerek** [comment]
Thanks. Removed these not needed dependencies, indeed that was also leftover: https://github.com/slajerek/MTEngineSDL/commit/e2c815a05838553a0884f690ece8a7205d3b2fed
