### ISSUE TITLE
Build failed on MacOS

### ISSUE THREAD

**Issue by tehashen** [slajerek/MTEngineSDL#3]
**Describe the bug**
The compilation failed on MacOS with Xcode because of an undeclared function (VID_PostInit()) in SYS_Startup.cpp.
I'm using Xcode 14 on a MacBook Air M2 with the latest version of Ventura.

**To Reproduce**
1. Clone the repository : git clone --recursive https://github.com/slajerek/MTEngineSDL.git
2. Build with Xcode or xcodebuild
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.3.1

**Additional context**

**Comment by slajerek** [comment]
@tehashen Hope that's been fixed, please check and confirm.

**Comment by tehashen** [comment]
@slajerek Thanks!
the last commit solved the issue.
I can compile Retro Debugger now too :)
